exp_id: 'channel_filter_LNK_try'
Model:
    name: 'KineticsChannelModelFilterBipolarNoNorm'
    checkpoint: ''
    noise: 0.
    linear_bias: False
    scale_kinet: False
    #n_units: 3
    recur_seq_len: 1
Data:
    batch_size: 512
    #data_path: '/home/xhding/tem_stim'
    #date: '20-09-15'