exp_id: 'kinetics_old_both'
Model:
    name: 'KineticsChannelModelFilterBipolarNoNorm'
    checkpoint: ''
    linear_bias: False
    n_units: 3
    ksr_gain: False
    k_chan: True
Data:
    batch_size: 512
    data_path: '/home/xhding/tem_stim'
    date: '20-09-15'
    stim: 'both'
    hs_mode: 'multiple'