exp_id: 'kinetics_1'
Model:
    name: 'KineticsModel'
    checkpoint: ''
    linear_bias: False
    n_units: 3
Data:
    batch_size: 512
    data_path: '/home/xhding/tem_stim'
    date: '20-12-02'
    hs_mode: 'single'
    stim: 'codebar'