exp_id: 'kinetics_old_one_pixel'
save_intvl: 1
Model:
    name: 'KineticsOnePixelChannel'
    checkpoint: '/home/xhding/saved_model/kinetics_old_both/epoch_045_loss_-67.27_pearson_natural_0.5080_pearson_noise_0.7204.pth'
    n_units: 3
Data:
    trunc_int: 2000
    loss_bin: 1000
    val_size: 30000
    batch_size: 5
    data_path: '/home/xhding/tem_stim'
    date: '20-09-15'
    stim: 'fullfield_whitenoise'
    stim_type: 'one_pixel'
    hs_mode: 'multiple'
    start_idx: 4000
Optimize:
    loss_fn: 'mse'
    lr: 0.2