exp_id: 'channel_filter_LNK_try'
Model:
    name: 'KineticsModel'
    checkpoint: ''
    linear_bias: False
    scale_kinet: False
    n_units: 3
    ka_offset: True
    ksr_gain: True
Data:
    batch_size: 512
    data_path: '/home/xhding/tem_stim'
    date: '20-09-15'
    hs_mode: 'single'