exp_id: 'kinetics_one_pixel'
save_intvl: 1
Model:
    name: 'KineticsOnePixel'
    #checkpoint: '/home/xhding/saved_model/kinetics_both/epoch_045_loss_-60.15_pearson_natural_0.4562_pearson_noise_0.4354.pth'
    #checkpoint: '/home/xhding/saved_model/kinetics_both/epoch_045_loss_-60.35_pearson_natural_0.4354_pearson_noise_0.4798.pth'
    checkpoint: '/home/xhding/saved_model/kinetics_both/epoch_045_loss_-62.71_pearson_natural_0.4564_pearson_noise_0.4508.pth'
    n_units: 4
    ksr_gain: False
Data:
    trunc_int: 2000
    loss_bin: 1000
    val_size: 30000
    batch_size: 5
    data_path: '/home/xhding/tem_stim'
    date: '21-01-26'
    stim: 'fullfield_whitenoise'
    stim_type: 'one_pixel'
    hs_mode: 'single'
    start_idx: 4000
Optimize:
    loss_fn: 'mse'
    lr: 0.2
Scheduler:
    mode: 'min'