exp_id: 'LNK'
img_shape: (100, 50, 50)
epoch: 50
Model:
    name: 'LNK'
    checkpoint: '/home/xhding/saved_model/LNK/epoch_045_loss_1.44_pearson_0.5086.pth'
    n_units: 1
Data:
    trunc_int: 2000
    loss_bin: 1000
    val_size: 30000
    batch_size: 5
    data_path: '/home/xhding/tem_stim'
    date: '20-09-15'
    stim: 'fullfield_whitenoise'
    
Optimize:
    lr: 0.05