exp_id: 'one_pixel_channel'
img_shape: (40, 50, 50)
epoch: 50
save_intvl: 1
Model:
    name: 'KineticsOnePixelChannel'
    #checkpoint: '/home/xhding/saved_model/channel_filter_both/epoch_010_loss_-63.31_pearson_natural_0.4721_pearson_noise_0.6993.pth'
    checkpoint: '/home/xhding/saved_model/channel_filter_both/epoch_020_loss_-65.15_pearson_natural_0.4804_pearson_noise_0.6849.pth'
    noise: 0.
    linear_bias: False
    scale_kinet: False
    n_units: 3
Data:
    trunc_int: 2000
    loss_bin: 1000
    val_size: 30000
    batch_size: 5
    data_path: '/home/xhding/tem_stim'
    date: '20-09-15'
    stim: 'fullfield_whitenoise'
    
Optimize:
    lr: 0.2