exp_id: 'BN_CNN_Stack_Poly'
img_shape: [40,50,50]
epoch: 100
Model:
    name: 'BN_CNN_Stack_poly'
    ksizes: (15, 11)
    checkpoint: '/home/xhding/saved_model/BN_CNN_Stack_Poly/epoch_085_loss_58.05_pearson_0.7305.pth'
    n_units: 6
    linear_bias: True
Data:
    date: '21-03-15'
    batch_size: 512
    data_path: '/home/xhding/tem_stim'
    stim: 'naturalscene'
    val_size: 10000
Optimize:
    trunc_intvl: 1
    l2: 1e-3
    l1: 1e-4