exp_id: 'BN_CNN_Stack_FC'
img_shape: [40,50,50]
epoch: 100
Model:
    name: 'BN_CNN_Stack_FC'
    ksizes: (15, 11, 9)
    checkpoint: ''
    linear_bias: True
    n_units: 11
Data:
    batch_size: 500
    data_path: '/home/TRAIN_DATA'
    date: '15-11-21b'
Optimize:
    trunc_intvl: 1
    l2: 1e-3
    l1: 1e-4
    lr: 1e-2
    oh_loss_scale: 7.