exp_id: 'BN_CNN_Stack_FC_2'
img_shape: [40,50,50]
epoch: 100
Model:
    name: 'BN_CNN_Stack_FC'
    ksizes: (15, 11, 9)
    checkpoint: '/home/xhding/saved_model/BN_CNN_Stack_FC/epoch_095_loss_-3.38_pearson_0.5292.pth'
    linear_bias: True
    n_units: 8
Data:
    date: '16-05-31'
    batch_size: 500
    data_path: '/home/xhding/tem_stim'
Optimize:
    trunc_intvl: 1
    l2: 1e-3
    l1: 1e-4