exp_id: 'channel_filter_LNK_NoNorm_UniScale'
Model:
    name: 'KineticsChannelModelFilterBipolarNoNorm'
    checkpoint: ''
    noise: 0.
    linear_bias: False
    scale_kinet: True
Optimize:
    lr: 1e-3